ALTER TABLE characters
  MODIFY level INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY xp INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY hp INT UNSIGNED NOT NULL DEFAULT 100,
  MODIFY ki INT UNSIGNED NOT NULL DEFAULT 100,
  MODIFY stamina INT UNSIGNED NOT NULL DEFAULT 100;
