CREATE DATABASE IF NOT EXISTS z_fusion
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE z_fusion;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(40) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS characters (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL UNIQUE,
  name VARCHAR(40) NOT NULL,
  gender ENUM('male', 'female') NOT NULL DEFAULT 'male',
  strength_points TINYINT UNSIGNED NOT NULL DEFAULT 5,
  speed_points TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ki_points TINYINT UNSIGNED NOT NULL DEFAULT 6,
  defense_points TINYINT UNSIGNED NOT NULL DEFAULT 4,
  level INT UNSIGNED NOT NULL DEFAULT 0,
  xp INT UNSIGNED NOT NULL DEFAULT 0,
  hp INT UNSIGNED NOT NULL DEFAULT 100,
  ki INT UNSIGNED NOT NULL DEFAULT 100,
  stamina INT UNSIGNED NOT NULL DEFAULT 100,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_characters_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inventory_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  item_key VARCHAR(60) NOT NULL,
  item_name VARCHAR(120) NOT NULL,
  slot_type VARCHAR(40) NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  equipped_slot VARCHAR(40) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_inventory_user (user_id),
  CONSTRAINT fk_inventory_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS fight_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  npc_name VARCHAR(120) NOT NULL DEFAULT 'Treniruočių kovotojas',
  result ENUM('win', 'loss', 'active') NOT NULL DEFAULT 'active',
  player_hp INT UNSIGNED NOT NULL DEFAULT 100,
  npc_hp INT UNSIGNED NOT NULL DEFAULT 100,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_fight_logs_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;
